FROM node:18 as build

ENV PORT=3000
ENV HOST=0.0.0.0

RUN npm i -g pnpm @nestjs/cli prisma
WORKDIR /app
COPY package.json ./

RUN pnpm i

COPY ./ ./
RUN pnpm prisma generate

RUN pnpm build

FROM node:18 as production

WORKDIR /app
COPY --from=build /app ./

CMD ["node", "dist/main"]

